### ISSUE TITLE
Created and add "Admin Login" with different credentials

### ISSUE THREAD

**Issue by siri0314** [WSUCEG-7140/Team-Rainbow--Quiz-Game-App#25]
Definition of Done:
Added "Admin Login" credentials with access to admin page.

**Comment by HarshaBojanki3** [comment]
![Image](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/assets/133044196/146e9f3f-086a-494c-9fbe-a20ca8871193)



- Created a Fire base admin credentials
