### ISSUE TITLE
Add disable quiz option in admin page for each quiz that allows admin to disable the quiz

### ISSUE THREAD

**Issue by Shirini4** [WSUCEG-7140/Team-Rainbow--Quiz-Game-App#54]
Definition of done:
Disable the old/unwanted quiz

**Comment by siri0314** [comment]
![Image](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/assets/37826044/5d600800-1ec6-45c4-9f34-6083ef6a5d10)
